#!/usr/bin/env python3
"""
GoAPILib Javadoc Scraper - v2
Scrapes Paper 1.21.8 + Spigot/Bukkit -> generates BridgePlugin.java
Usage:
  python3 scrape_goapi.py
  python3 scrape_goapi.py --dry-run
"""

import re, sys, json, time
from urllib.request import urlopen, Request
from html.parser import HTMLParser
from pathlib import Path

TARGETS = {
    "paper":  {"base": "https://jd.papermc.io/paper/1.21.8",       "label": "Paper 1.21.8"},
    "spigot": {"base": "https://hub.spigotmc.org/javadocs/bukkit",  "label": "Spigot/Bukkit"},
}
MC_MIN    = "1.20.1"
CACHE_DIR = Path(".scrape_cache")
OUT_JAVA  = Path("GoAPI/src/main/java/com/example/goapi/bridge")
OUT_RES   = Path("GoAPI/src/main/resources")

PAPER_ONLY_PKGS = [
    "com.destroystokyo.paper.event",
    "io.papermc.paper.event",
]
EVENT_PKGS = ["org.bukkit.event"] + PAPER_ONLY_PKGS
FQCN_PRIORITY = [
    "io.papermc.paper.event",
    "com.destroystokyo.paper.event",
    "org.bukkit.event",
]
ABSTRACT_BASE_EVENT_NAMES = {
    "Event",
    "BlockEvent",
    "EntityEvent",
    "HangingEvent",
    "InventoryEvent",
    "InventoryInteractEvent",
    "PlayerEvent",
    "PluginEvent",
    "ServerEvent",
    "ServiceEvent",
    "VehicleCollisionEvent",
    "VehicleEvent",
    "WorldEvent",
}
HIGH_FREQUENCY_EVENT_NAMES = {
    "PlayerMoveEvent",
    "BlockPhysicsEvent",
    "BlockRedstoneEvent",
    "EntityMoveEvent",
    "ClientTickEndEvent",
}
EXCLUDED_EVENT_NAMES = ABSTRACT_BASE_EVENT_NAMES | HIGH_FREQUENCY_EVENT_NAMES

def fetch(url):
    CACHE_DIR.mkdir(exist_ok=True)
    key = CACHE_DIR / (re.sub(r"\W", "_", url) + ".html")
    if key.exists():
        print(f"  [cache] {url}")
        return key.read_text("utf-8")
    for i in range(3):
        try:
            req = Request(url, headers={"User-Agent": "Mozilla/5.0 GoAPILib/2.0"})
            with urlopen(req, timeout=20) as r:
                text = r.read().decode("utf-8", errors="ignore")
            key.write_text(text, "utf-8")
            time.sleep(1.0)
            return text
        except Exception as e:
            if i == 2:
                print(f"  [WARN] {url}: {e}")
                return ""
            time.sleep(2 * (i + 1))
    return ""

class ClassIndexParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.entries = []
        self._href = None

    def handle_starttag(self, tag, attrs):
        if tag == "a":
            href = dict(attrs).get("href", "")
            if re.match(r"[\w/]+\.html", href):
                self._href = href

    def handle_data(self, data):
        if self._href and data.strip():
            fqcn = self._href.replace("/", ".").removesuffix(".html")
            self.entries.append({"name": fqcn.split(".")[-1], "fqcn": fqcn})
            self._href = None

    def handle_endtag(self, tag):
        if tag == "a":
            self._href = None

def is_event(e):
    return (
        any(e["fqcn"].startswith(p) for p in EVENT_PKGS)
        and e["name"].endswith("Event")
        and not e["name"].startswith("Abstract")
        and e["name"] not in EXCLUDED_EVENT_NAMES
    )

def is_paper_only(fqcn):
    return any(fqcn.startswith(p) for p in PAPER_ONLY_PKGS)

def priority_of(fqcn):
    for i, p in enumerate(FQCN_PRIORITY):
        if fqcn.startswith(p):
            return i
    return len(FQCN_PRIORITY)

def dedupe_by_fqcn(entries):
    seen = set()
    out = []
    for e in entries:
        fqcn = e["fqcn"]
        if fqcn in seen:
            continue
        seen.add(fqcn)
        out.append(e)
    return out

def dedupe_by_name(entries):
    order = []
    picked = {}
    for e in entries:
        name = e["name"]
        if name not in picked:
            order.append(name)
            picked[name] = e
            continue
        cur = picked[name]
        if (priority_of(e["fqcn"]), e["fqcn"]) < (priority_of(cur["fqcn"]), cur["fqcn"]):
            picked[name] = e
    return [picked[name] for name in order]

def gen_java(common, paper_only):
    total = len(common) + len(paper_only)

    lines = [
        "package com.example.goapi.bridge;",
        "",
        "import com.example.goapi.GoAPIPlugin;",
        "import org.bukkit.event.EventHandler;",
        "import org.bukkit.event.EventPriority;",
        "import org.bukkit.event.Listener;",
        "// Event classes are referenced by FQCN in handler signatures.",
        "import java.util.LinkedHashMap;",
        "import java.util.Map;",
        "",
        "/**",
        f" * Auto-generated by scrape_goapi.py - DO NOT EDIT",
        f" * MC compat: {MC_MIN}+  |  common: {len(common)}  paper-only: {len(paper_only)}  total: {total}",
        " */",
        "public class BridgePlugin implements Listener {",
        "",
        "    private final GoAPIPlugin api;",
        "    public BridgePlugin(GoAPIPlugin api) { this.api = api; }",
        "",
    ]

    for e in common:
        lines += [
            f"    // {e['fqcn']}",
            f"    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = false)",
            f"    public void on{e['name']}({e['fqcn']} e) {{",
            f'        Map<String, Object> d = new LinkedHashMap<>();',
            f'        d.put("_api", "bukkit");',
            f'        api.getDispatcher().dispatch("event.{e["name"]}", d, e);',
            f"    }}",
            "",
        ]

    for e in paper_only:
        lines += [
            f"    // {e['fqcn']} [Paper only]",
            f"    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = false)",
            f"    public void on{e['name']}({e['fqcn']} e) {{",
            f"        if (!api.isPaper()) return;",
            f'        Map<String, Object> d = new LinkedHashMap<>();',
            f'        d.put("_api", "paper");',
            f'        api.getDispatcher().dispatch("event.{e["name"]}", d, e);',
            f"    }}",
            "",
        ]

    lines.append("}")
    return "\n".join(lines) + "\n"

def gen_plugin_yml():
    return (
        "name: GoAPI\n"
        "version: 1.0.0\n"
        "main: com.example.goapi.GoAPIPlugin\n"
        "api-version: 1.20\n"
        "description: Java <-> Go Bridge API Library\n"
        "authors: [generated]\n"
    )

def main():
    dry = "--dry-run" in sys.argv
    entries = {"paper": [], "spigot": []}

    for key, cfg in TARGETS.items():
        print(f"\n[{cfg['label']}] fetching ...")
        if dry:
            print("  (dry-run: skipped)")
            continue
        html = fetch(f"{cfg['base']}/allclasses-index.html")
        p = ClassIndexParser()
        p.feed(html)
        all_events = dedupe_by_fqcn([e for e in p.entries if (
            any(e["fqcn"].startswith(pfx) for pfx in EVENT_PKGS)
            and e["name"].endswith("Event")
            and not e["name"].startswith("Abstract")
        )])
        entries[key] = [e for e in all_events if is_event(e)]
        excluded = len(all_events) - len(entries[key])
        print(f"  events found: {len(entries[key])} (excluded: {excluded})")

    paper_fqcn = {e["fqcn"] for e in entries["paper"]}
    spigot_fqcn = {e["fqcn"] for e in entries["spigot"]}
    # Compile target is Paper API. "common" must be the intersection.
    common = dedupe_by_name([e for e in entries["spigot"] if e["fqcn"] in paper_fqcn])
    paper_only = dedupe_by_name([e for e in entries["paper"] if e["fqcn"] not in spigot_fqcn])

    print(f"\n=== Classification ===")
    print(f"  Bukkit/Spigot common : {len(common)}")
    print(f"  Paper-only           : {len(paper_only)}")

    OUT_JAVA.mkdir(parents=True, exist_ok=True)
    OUT_RES.mkdir(parents=True, exist_ok=True)

    (OUT_JAVA / "BridgePlugin.java").write_text(gen_java(common, paper_only), "utf-8")
    (OUT_RES  / "plugin.yml").write_text(gen_plugin_yml(), "utf-8")
    Path("events.json").write_text(
        json.dumps({"common": common, "paper_only": paper_only}, ensure_ascii=False, indent=2), "utf-8"
    )

    print("\n=== Generated ===")
    print(f"  {OUT_JAVA}/BridgePlugin.java")
    print(f"  {OUT_RES}/plugin.yml")
    print(f"  events.json")

    print("\n=== Sample mapping ===")
    for e in (common + paper_only)[:10]:
        tag = "[paper]" if is_paper_only(e["fqcn"]) else ""
        print(f"  {e['name']:<45} event.{e['name']} {tag}")

if __name__ == "__main__":
    main()
